version: '3.8'
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:dev
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      WEBUI_AUTH: "True"
    volumes:
      - /home/daniel/data/openwebui:/app/backend/data
    restart: always
