version: '3.8'
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:dev
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      WEBUI_AUTH: "True"
    volumes:
      - /home/daniel/data/openwebui:/app/backend/data
    restart: always

  backup:
    image: alpine
    container_name: open-webui-backup
    volumes:
      - /home/daniel/data/openwebui:/data/source:ro
      - /home/daniel/data/openwebui-backups:/data/backups
    command: >
      sh -c '
        while true; do
          BACKUP_NAME="backup-$$(date +%Y%m%d-%H%M%S).tar.gz"
          tar czf /data/backups/$$BACKUP_NAME -C /data/source .
          find /data/backups -type f -mtime +30 -delete
          sleep 604800
        done
      '
    restart: always
